dateModified: 1770908690
email:
  fromEmail: mark@markhuot.com
  fromName: 'Craft 5'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: /uploads
meta:
  __names__:
    0df1c5a0-f2fd-43b7-b0f4-95d51e3823e7: News # News
    1ab796d1-aa8e-4bba-9231-712406fed18f: Pages # Pages
    5d1f19f0-18d8-474b-aab5-c676c7ad9fee: 'Content Builder' # Content Builder
    8e93f202-c69f-4b89-89e5-cd19d66bcc31: Pages # Pages
    23c47a1d-84e6-42e8-aa88-822d42392852: News # News
    416fcc94-20bc-4fda-a860-febe8ad45482: Heading # Heading
    03034b8d-617d-4062-a124-76ac48ad6ceb: 'Craft 5' # Craft 5
    5275552e-1e3e-4fe3-af09-3974f89f2cd9: 'Plain Text' # Plain Text
    ca510033-f66c-4cd3-9577-bc4ed6a74c2a: Uploads # Uploads
    dff954b5-6c1a-4334-8981-f325121886fd: 'Craft 5' # Craft 5
    e9a2bd3d-0130-4733-a448-2dca491bff14: Body # Body
    fb13a791-69be-44a4-aa52-93c37a9fb32e: 'Call to Action' # Call to Action
plugins:
  skills:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft 5'
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
